version: '3.9'

services:
  app:
    build: .
    container_name: nextjs-app
    ports:
      - '3000:3000'
    environment:
      DB_HOST: db
      DB_USER: team_user
      DB_PASSWORD: SkWarriors23336
      DB_NAME: smart_finder
      DB_PORT: 3306
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: smart_finder
      MYSQL_USER: team_user
      MYSQL_PASSWORD: SkWarriors23336
    ports:
      - "3307:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
